name: Accessibility Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install axe-linter
        run: npm install -g @axe-devtools/linter

      - name: Run axe-linter
        run: axe-linter . --json | tee axe-results.json
